import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateReport = ({
  analysis,
  fileName = "Resume.pdf",
  jobDescription = "",
}) => {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();

  // ========= Header =========

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("AI Resume Analysis Report", pageWidth / 2, 18, {
    align: "center",
  });

  doc.setTextColor(0, 0, 0);

  // ========= Resume Info =========

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  doc.text(`Resume: ${fileName}`, 15, 40);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    15,
    47
  );

  doc.text(
    `Job Description: ${
      jobDescription ? "Provided" : "Not Provided"
    }`,
    15,
    54
  );

  // ========= Scores =========

  autoTable(doc, {
    startY: 62,
    head: [["Metric", "Score"]],
    body: [
      ["ATS Score", `${analysis.ats_score}%`],
      ["Match Percentage", `${analysis.match_percentage}%`],
      ["Formatting Score", `${analysis.formatting_score}%`],
      ["Grammar Score", `${analysis.grammar_score}%`],
      ["Keyword Score", `${analysis.keyword_score}%`],
    ],
    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  let y = doc.lastAutoTable.finalY + 12;

  // ========= Summary =========

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("AI Summary", 15, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const summary = doc.splitTextToSize(
    analysis.summary || "",
    180
  );

  doc.text(summary, 15, y);

  y += summary.length * 6 + 8;

  // ========= Helper =========

  const addList = (title, items) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);

    doc.text(title, 15, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    if (!items || items.length === 0) {
      doc.text("None", 20, y);
      y += 10;
      return;
    }

    items.forEach((item) => {
      if (y > 280) {
        doc.addPage();
        y = 20;
      }

      const lines = doc.splitTextToSize(
        `• ${item}`,
        175
      );

      doc.text(lines, 20, y);

      y += lines.length * 6;
    });

    y += 6;
  };

  // ========= Sections =========

  addList("Strengths", analysis.strengths);

  addList("Areas to Improve", analysis.weaknesses);

  addList("Missing Skills", analysis.missing_skills);

  addList("Missing Keywords", analysis.missing_keywords);

  // ========= Suggestions =========

  if (y > 250) {
    doc.addPage();
    y = 20;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);

  doc.text("AI Suggestions", 15, y);

  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  if (
    analysis.suggestions &&
    analysis.suggestions.length > 0
  ) {
    analysis.suggestions.forEach((suggestion, index) => {
      if (y > 275) {
        doc.addPage();
        y = 20;
      }

      doc.setFont("helvetica", "bold");

      doc.text(
        `${index + 1}. ${suggestion.title}`,
        15,
        y
      );

      y += 6;

      doc.setFont("helvetica", "normal");

      const description = doc.splitTextToSize(
        suggestion.description,
        175
      );

      doc.text(description, 20, y);

      y += description.length * 6 + 5;

      if (suggestion.priority) {
        doc.setTextColor(220, 38, 38);

        doc.text(
          `Priority: ${suggestion.priority}`,
          20,
          y
        );

        doc.setTextColor(0, 0, 0);

        y += 8;
      }
    });
  }

  // ========= Footer =========

  const pages = doc.getNumberOfPages();

  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(
      "Generated by AI Resume Analyzer",
      pageWidth / 2,
      290,
      {
        align: "center",
      }
    );
  }

  doc.save("AI_Resume_Report.pdf");
};  